name: AIS Collector

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Télécharger le repo
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installer les librairies
        run: pip install -r requirements.txt

      - name: Lancer le script
        run: python data_collector.py
      - name: Commit et push des données
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/*.csv
          git commit -m "Update AIS dataset" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/ZouarhiYassmin/ais-dataset-vesselfinder.git
